### ISSUE TITLE
Creating an overlay with Azul

### ISSUE THREAD

**Issue by Pzixel** [maps4print/azul#102]
Hey guys. I'm trying to write a simple desktop app which should be an overlay. It means it should be a transpartent topmost window without standard buttons. In C# terms:

```cs
var form = new Form {
  FormBorderStyle = FormBorderStyle.None,
  Opacity = 0.3,
  TopMost = true
}
```

How do I do it with Azul?

**Comment by fschutt** [comment]
Well, there are a few problems regarding window transparency, see #65, but otherwise, you'd do it when creating the window:

```rust
let mut window_options = WindowCreateOptions::default();

window_options.state.has_decorations = false;
window_options.background = Some(ColorF { r: 0.0, g: 0.0, b: 0.0, a: 0.3 });
window_options.state.is_top_level_window = true;

let window = Window::new(window_options, css::native()).unwrap();
```

Note: `state.is_top_level_window` doesn't exist yet, but that's how it would be implemented (in the future).

**Comment by Pzixel** [comment]
So, it's currently not possible. Sad to hear it.

Btw, how do I set `ColorF`? It seems that all dependencies are wendored as hell and I just get `expected ColorF but found ColorF` when using `webrender_api` from crates.io. I tried to search for examples, but I didn't find relevant toml.

**Comment by fschutt** [comment]
Just use the ColorF from azuls API - `use azul::prelude::ColorF;`. Of course if you import a similar-looking type from a completely different crate then the type doesn't match. Why are you trying to import `webrender_api` from crates.io, you shouldn't need to do that? It's the completely wrong version of webrender, so obviously the type doesn't match.

Try to build the documentation using `cargo doc --open`, it will give much more information and a searchable API in case you get stuck.

**Comment by Pzixel** [comment]
> Why are you trying to import webrender_api from crates.io, you shouldn't need to do that?

Because that's what `rustc` told me

```rust
error[E0308]: mismatched types
  --> src\main.rs:17:33
   |
17 |     window_options.background = ColorF { r: 0.0, g: 0.0, b: 0.0, a: 0.3 };
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `webrender_api::color::ColorF`, found struct `azul_css::css_properties::ColorF`
   |
   = note: expected type `webrender_api::color::ColorF`
              found type `azul_css::css_properties::ColorF`

error: aborting due to previous error
```

**Comment by fschutt** [comment]
Okay, I'm not sure if you are still having issues but I just wanted to respond to your comment about me not being responsive enough - the reason why I didn't say anything was simply because *you didn't ask a question*. You asked about the `ColorF` issue and whether azul supports top-level windows. My answer was to `use azul::prelude::ColorF;` and no to the second question. So I did answer your questions and considered this issue closed, that's why I didn't respond. 

rustc not suggesting the correct type isn't a problem of azul, it's a bug in the rust compiler. I know it because this also happens with serde, whether dependencies are vendored or not. You need to use the exact type from the exact library version you're using, otherwise you get a type mismatch. So if you're still having issues with that - again, `use azul::prelude::ColorF;` is the solution.

If you're still having compilation errors beyond that, well, you need to post them - I can't magically know if you're having problems. If not, I'm considering this issue closed (since I already know about the transparency issues, so there's no point in having two separate issues for the same problem). Thank your for reporting these problems.

**Comment by fschutt** [comment]
I think I know what your problem was - since you were posting about problems after I posted the solution, I decided to look into it and found that the `ColorF` was not properly exposed in the API. I assumed that you simply didn't try my solution, which is why you posted the same issue again, even after I told you the solution to be `use azul::prelude::ColorF;`. A comment like "still doesn't work" would have been helpful, since I didn't know that you were **still** having issues.

This issue should be fixed by https://github.com/maps4print/azul/commit/2463ca59bfc9bf0acf852bef0230bd4098d40d94. Thank you for reporting and sorry for the inconvenience.
