### ISSUE TITLE
Winit v0.18.1

### ISSUE THREAD

**Issue by knappador** [maps4print/azul#109]
## Description
Winit minor version 0.18.1 is available

## Describe your solution
I can PR the Cargo update

## Are there alternatives or drawbacks?
The future leans forward

## Is this a breaking change
Supposedly a minor version bump. 

## Additional notes
Supposedly there's a bot for generating version bump notifications
https://dependabot.com/

**Comment by knappador** [comment]
https://github.com/maps4print/azul-dependencies/blob/master/glutin-0.19.0/Cargo.toml#L41

```
│   ├── glium v0.22.0 (https://github.com/maps4print/azul-dependencies?rev=055034bd642496cf91730a3fb4bcf3250da47772#055034bd)
│   │   ├── fnv v1.0.6 (https://github.com/maps4print/azul-dependencies?rev=055034bd642496cf91730a3fb4bcf3250da47772#055034bd)
│   │   ├── glutin v0.19.0 (https://github.com/maps4print/azul-dependencies?
...
│   │   │   ├── winit v0.18.0 (https://github.com/maps4print/azul-dependencies?rev=055034bd642496cf91730a3fb4bcf3250da47772#055034bd)
```
As pointed out in #57 

Skip ahead to https://github.com/maps4print/azul/issues/95 for popcorn.

Closing as duplicate and shifting focus to root causes in #95

**Comment by fschutt** [comment]
Don't worry, I upgrade dependencies from time to time. But not every minor version release warrants an upgrade. Second, the forked version of winit also has some changes, mainly due to disabled unnecessary dependencies. It's not the same code as winit 0.18, it's a custom fork. So when upgrading, I need to merge over the patches / changes.
