### ISSUE TITLE
Text input won't report Ctrl as modifier

### ISSUE THREAD

**Issue by akiross** [maps4print/azul#111]
I was experimenting with Azul (thanks for it, by the way!) and I based myself on the calculator example.
I registered two handlers, one to handle `WindowEventFilter::TextInput` and one for `WindowEventFilter::VirtualKeyDown`. I would like to detect when a text key is being pressed with one or more modifiers. I use the keyboard state to check if the modifiers are being pressed using `(alt|ctr|shift|super)_down` booleans.

While I can correctly detect the pressure of any combination of modifiers and one text key in the `VirtualKeyDown` handler, I am unable to do so in `TextInput` handler, specifically, my `handle_text_input` callback is not called on Ctrl+Key combinations. Shift, Alt and Super seems to work correctly.

Why is it so? And which method is recommended to detect keys with modifiers?

**Comment by fschutt** [comment]
TextInput does not fire for any control (or "non-printable") characters. Meaning, if you just add a `TextInput` listener, your callback won't be invoked when you press `Ctrl + V`. If you have a text field and you want to detect both Unicode text input and actions such as `Ctrl + V`, you need two callbacks, one for listening on control characters (using `On::VirtualKeyDown`) and one for Unicode text input (using `On::TextInput`).

Inside of the `TextInput` callback, you should only access the `.latest_char`, while in the `VirtualKeyDown` callback you should access the `.latest_virtual_key`. This is because VirtualKeyDown only sets the virtual key (such as `VirtualKey::Ctrl, VirtualKey::V`) - however that virtual key does not have to correspond to the keyboard layout, for example the virtual key might be `VirtualKey::S`, while the `latest_char` is actually an `O` because the user has a Dvorak keyboard layout (or a Russian / Chinese / non-US keyboard). If you'd only use virtual keys, there'd be no way of getting non-ASCII text input.

So: If you want to listen to key combinations such as Ctrl+C, make a callback using `On::VirtualKeyDown`. If you want to listen to (Unicode) text input, use `TextInput`. If you want to do both, you'll need two callbacks.

Note that `On::VirtualKeyDown` gets attached to the *window*, not the DOM element itself. It was originally intended for implementing hotkey combinations, so it can fire even when the user isn't hovering over the element. You can of course configure that by using `EventFilter::Hover` or `EventFilter::Focus` instead if you'd like the `VirtualKeyDown` to fire only when the user is hovering or focusing the DOM element. Hope that clears things up.

**Comment by akiross** [comment]
In fact, I have to detect hotkey combinations (I am trying to implement a vi-like modal interface), so it's actually better to have `VirtualKeyDown` bound to the window instead of the DOM.

Your feedback is very helpful, thanks a lot!
