### ISSUE TITLE
OpenGL texture only briefly renders

### ISSUE THREAD

**Issue by gmorenz** [maps4print/azul#114]
## Description

I'm using the code provided below, which is a mildly adapted (just to update to azul changes) version of the OpenGL code in the wiki. The output is the following:

 - Before call to layout 1: The screen hasn't been rendered
 - After call to layout 1: The screen is black
 - After call to layout 2: The screen is black
 - After call to layout 3: The screen is green (as expected!)
 - After call to layout 4: The screen is green (again!)
 - After call to layout 5 and onwards: The screen is white

When the pause in the code below is removed these 5 calls happen in something like a quarter of a second (just eyeballed).

What I'd like to see: Ideally after all the calls to layout the screen would be green. At the very least though it should not turn white...

Resizing the window between every layout doesn't seem to do anything except cause the positioning of the rendered green texture to be 1 frame out of date.

## Version / OS

* azul version:   e6dfa13
* Operating system: Linux
* Windowing system (X11 or Wayland, Linux only): X11

## Steps to Reproduce

Run this code, it blocks in layout after printing "Pause" until you feed it a newline:

```
extern crate azul;

use azul::prelude::*;
use azul::azul_dependencies::glium::Surface;
use std::time::Duration;

macro_rules! CSS_PATH { () => (concat!(env!("CARGO_MANIFEST_DIR"), "/src/main.css")) }

struct OpenGlAppState { }

impl Layout for OpenGlAppState {
    fn layout(&self, _info: LayoutInfo<Self>) -> Dom<Self> {
        println!("Pause");
        let mut input = String::new();
        let _ = std::io::stdin().read_line(&mut input);
        Dom::new(NodeType::GlTexture((
            GlTextureCallback(render_my_texture), 
            StackCheckedPointer::new(self, self).unwrap()
        )))
    }
}

fn render_my_texture(
    _state: &StackCheckedPointer<OpenGlAppState>, 
    info: LayoutInfo<OpenGlAppState>, 
    hi_dpi_bounds: HidpiAdjustedBounds) 
-> Option<Texture> 
{
    let texture = info.window.read_only_window().create_texture(
        hi_dpi_bounds.physical_size.width as u32, 
        hi_dpi_bounds.physical_size.height as u32
    );

    texture.as_surface().clear_color(0.0, 1.0, 0.0, 1.0);
    Some(texture)
}

fn main() {
    let app = App::new(OpenGlAppState { }, AppConfig::default());

    #[cfg(debug_assertions)]
    let window = Window::new_hot_reload(
        WindowCreateOptions::default(), 
        css::hot_reload_override_native(CSS_PATH!(), Duration::from_millis(500))
    ).unwrap();

    #[cfg(not(debug_assertions))]
    let window = Window::new(
        WindowCreateOptions::default(), 
        css::override_native(include_str!(CSS_PATH!())).unwrap()
    ).unwrap();

    app.run(window).unwrap();
}
```

## Additional Information

Are issues like this and the previous one I opened (newlines breaking formatting) useful at this stage in development? I.e. should I continue filing them when I come across issues while checking out what  Azul can do?

**Comment by fschutt** [comment]
Yeah, I know about this bug and it has to do with glium, the state management inside of glium prevents the shader from actually drawing - the problem is that glium doesn't integrate very well with external OpenGL and assumes that it is the only toolkit that messes with the OpenGL state.

It's better to just file the bugs, this way I don't forget about them. I think to work around this specific bug, you need to use a shader or raw OpenGL calls - so that glium notices that you actually changed the OpenGL state.

**Comment by fschutt** [comment]
Okay, I've made some improvements in https://github.com/maps4print/azul/commit/742450435450504f9768f6c5fd9fec8a324540ee - the layout() function isn't called twice anymore and the window is hidden until the first redraw (to prevent a black screen / flickering on startup). Also added your example as `opengl.rs`. The white screen is still a problem, but at least it's not flickering anymore.

**Comment by Phlosioneer** [comment]
Does `ReadOnlyWindow::unbind_framebuffer()` fix this?

**Comment by Phlosioneer** [comment]
I've run into this issue. I can add a bit more info: If you resize the window between frames (i.e. between pauses, in the above example), the rest of the window is red. The white only covers the exact size of the texture from the _previous_ frame.

**Comment by Phlosioneer** [comment]
@fschutt Hey, I'd like a bit of help.

I've made a patch for Glium to (unsafely) force the program handle to 0, so that it will reload the shaders and draw them correctly. I've gone through all the work required to modify azul and azul-dependencies to use the patched Glium. However, I don't know where to insert the reset. I located the code where webrender is rendering (`App::render_inner`, the line `app_resources.fake_display.renderer.as_mut().unwrap().render(framebuffer_size).unwrap();`). I've also located the code where GlTextureCallbacks are run (`display_list::push_opengl_texture`).

However, those functions are using `gleam::Gl` instances, and I don't understand how that relates to Glium. Gleam _seems_ to be direct GL interaction. So I don't know where to put the reset; but more importantly, I don't know how to get the `glium::context::Context` struct that needs to be reset. The only kind of "context" object I can get, as far as I understand, is a `gleam::Gl` instance, which has no knowledge of Glium at all.

Do you have any advice or insights? If I can't figure this out, the alternative is to try and patch webrender instead... and that's much, much more difficult. Further, the webrender team have decided not to fix this issue, while Glium would be interested in a force-reset to avoid this kind of issue.

**Comment by fschutt** [comment]
@Phlosioneer Yeah, sorry to say this but you might have done this for nothing, because I decided to remove glium in the `gl_rework` branch altogether. As I suspected, this was a bug because glium decides to be smart about caching the OpenGL state, but that is a problem when non-glium libraries such as webrender mess with the OpenGL state. [This has been a source of bugs in the past](https://github.com/servo/webrender/issues/3262) and I've already reported this, but [glium maintainers don't want to fix it](https://github.com/glium/glium/issues/1696#issuecomment-404435503) - so I've decided to remove glium and use raw GL calls instead. This is more unsafe, but easier to debug.

`gleam::Gl` is a trait around an OpenGL context: https://docs.rs/gleam/0.6.17/gleam/gl/trait.Gl.html - it's so that other, non-Azul or even non-Rust programs can interact with Azuls GL context, without having to depend on gliums types (which is impossible for C programs). You can initializes a `Gl` context from an OpenGL context pointer - which is FFI compatible.

Check the `gl_rework` branch (although it might not compile at the moment).

**Comment by Phlosioneer** [comment]
Alright, thanks though. I'll take a look at that branch. I've learned a bunch about GL anyway, at least.

**Comment by fschutt** [comment]
This is also fixed, because the OpenGL code now has a different API, that requires you to do direct OpenGL calls (which also has more flexibility). See the `/examples/opengl/opengl.rs` for an example on how to use the new API, the wiki is outdated.
