### ISSUE TITLE
On::TextInput, On::FocusReceived not firing

### ISSUE THREAD

**Issue by kurtlawrence** [maps4print/azul#117]
## Description

Take code such as

```rust
			Label::new(text).dom()
				.with_callback(On::TextInput, Callback(on_text_input))
				.with_callback(On::VirtualKeyDown, Callback(on_vk_keydown))
				.with_callback(On::FocusReceived, Callback(|_,_| {
					println!("focus received");
					DontRedraw
				}))
```

and the `TextInput` and `FocusReceived` callbacks don't fire. `VirtualKeyDown` still fires.

Perusing the code it seems to be a focus issue, given both those variants use the `FocusEventFilter`.

Building a layout with `TextInput` widget is also broken.

**Comment by fschutt** [comment]
If you want FocusEvent, you have to at least set `.focusable(true)`, otherwise it's not going to fire. But even then it will likely not fire because focus searches for the nearest focusable elements (only one element can be focused at all times) - which, in this case will be the text input, not your wrapper DOM.

What version of azul are you using? There were bugs related to TextInput (see #105), but those are already fixed.

**Comment by kurtlawrence** [comment]
I am on the master branch, just double checked.

I am getting compilation errors for `.focusable(true)`, I can't find any reference to that function.

I double checked the documentation and source code, no `.focusable()` function.

**Comment by fschutt** [comment]
Try `.with_tab_index(TabIndex::Auto)`. This is also probably the reason why TextInput doesn't work, because the field isn't focus-able (and TextInput assumes a focus-able text field). Maybe in the future it would be best to get rid of `.with_tab_index` and instead just look at the callback type (if there is any `FocusEventFilter`, treat the div like `focusable = "true"` is set).

**Comment by kurtlawrence** [comment]
Thanks @fschutt, that has made it focusable.

The `TextInput` not working was a bum-steer, I found I had commented out the `.bind` function.

Thanks for getting back to me so quickly.
