### ISSUE TITLE
crates.io not found

### ISSUE THREAD

**Issue by uncode** [maps4print/azul#12]
https://crates.io/search?q=azul

**Comment by fschutt** [comment]
Yeah I know, it's not on crates.io yet since it's not very stable or particularly useful. Doesn't make sense to publish a half-finished framework, does it? You can look at the [0.1 milestone board](https://github.com/maps4print/azul/projects/1) to see what I think is necessary for a 0.1 release. For now you can use `azul = { git = "https://github.com/maps4print/azul" rev = "the-latest-commit-hash-here" }` if you want to use it from cargo.

**Comment by uncode** [comment]
thk
