### ISSUE TITLE
How to bind a click event on an XML component to a rust callback? 

### ISSUE THREAD

**Issue by dondreytaylor** [maps4print/azul#121]
Was wondering if it were possible to bind a click event in the form of a mouseup on an XML component. The XML seems like a way easier way to bootstrap my UI, so I'm exploring ways to work with it. In the future, I'd love to start contributing to your documentation, really love the project so far. 

Basically trying to do this:

```rust 
let button = Button::with_label("Update counter").dom()
            .with_callback(On::MouseUp, Callback(update_counter));
```
but doing the binding in the XML
```rust 
<component name="button">
    <div class="__azul-native-button" onclick="update_counter">
        <p>Update Counter</p>
     </div>
</component>
```
Any help would be greatly appreciated.

**Comment by fschutt** [comment]
Yeah, XML is still \*quite\* a work in progress - right now, no, this isn't possible - the goal of the XML system was to enable hot-reloading for UIs and better prototyping, so that you could prototype UIs in XML, then compile the XML to Rust code (and then attach your callbacks to that auto-generated Rust code) and turn that Rust code into a "component" itself (which could then be used from XML). The goal was to get around the long compilation time - but if you want to attach callbacks inside of XML, you'd first have to write these callbacks in Rust, so you can't avoid the compilation.

It would be fairly easy to add this feature, though - the XML generates its DOM via an `XmlComponentMap`, which stores all the components. You'd have to modify it to also store callbacks, for example:

```rust
fn layout(&self, _: LayoutInfo<T>) -> Dom<T> {
    let mut components = XmlComponentMap::default();
    // This API doesn't exist yet, would have to be written
    components.register_callback("my-callback-identifier", my_callback);
    Dom::from_str("<app><div onclick="my-callback-identifier" /></app>")
}

fn my_callback(_: AppState<T>, _: CallbackInfo<T>) { /**/ }
```

Ideally the XML-to-Rust compiler could use the identifier to generate the appropriate code, but azul is still a long way off from that.

**Comment by dondreytaylor** [comment]
Ah okay, thanks for explaining this. Totally makes sense. The long compile time is certainly cumbersome to workaround. Nonetheless, an API like this would be neat. I'm going to check out your roadmap and see what I can do to help out.
