### ISSUE TITLE
Referring to images both in XML and CSS

### ISSUE THREAD

**Issue by dondreytaylor** [maps4print/azul#122]
Trying to figure out how to work with images. Based on the documentation, it shows that you need to first include the image data using the `add_image` function and then reference it using the ID both within the DOM and/or CSS. 

It appears that `add_image` is not defined on `App` but instead on `AppResources`, is there an example of how it can be referenced?  I tried a few different ways, but it gives me errors that `add_image` is not defined.

This one states that `ImageType::Jpeg` is undefined, when I run the example 
https://github.com/maps4print/azul/blob/master/examples/hot_reload.rs

```rust 
     let mut app = App::new(MyDataModel {}, AppConfig::default());
    app.add_image("Cat01", &mut TEST_IMAGE, ImageType::Jpeg).unwrap();
```
Also tried this one after I discovered that `add_image` was defined on `AppResources` instead of directly on `App`. This one told me that `add_image` was not defined within the scope. Both examples were called from my main function.

```rust
     let mut app = App::new(MyDataModel {}, AppConfig::default());
     app.app_state.resources.add_image("Cat01", &mut TEST_IMAGE, ImageType::Jpeg).unwrap();
```

Furthermore,  once the image has been added was curious how I could go about referencing it within the CSS and DOM. 

Appreciate any help.

**Comment by fschutt** [comment]
`add_image` should be defined on both the `App`, `AppState` and `AppResources` (the `App` owns the `AppResources`, it just forwards all the calls to `self.resources`), but it's behind a feature flag, you have to enable `--features="image_loading"`. The `add_image` function itself is just generated by a macro, maybe your documentation tool doesn't expand macros.

https://github.com/maps4print/azul/blob/809cc3cf4a2ca163d6826ee017be72d1f1be8d9b/azul/src/app.rs#L343

https://github.com/maps4print/azul/blob/809cc3cf4a2ca163d6826ee017be72d1f1be8d9b/azul/src/macros.rs#L228-L229

You have to create an `ImageId` manually using `app_resources.add_css_image_id("Cat01")` - which you can then store in your app data and use to identify the image in the DOM. The "CSS image ID" is the "Cat01", while the "Image ID" is just a number like "image 0". This is a bit unpractical to manage, which is why you can also throw the `ImageId` away after you've called `add_image` with it and use the `LayoutInfo` (the second parameter of the `layout()` function), to look up the `ImageId` for `"Cat01"` inside of the layout function:

```rust
fn layout(&self, info: &LayoutInfo<T>) -> Dom<T> {
     let image_id = info.resources.get_css_image_id("Cat01").unwrap();
     Dom::image(image_id)
}
```

In CSS code, you can just use the `image("Cat01")` to identify the image. I know, this API is (still) a bit confusing right now, in the future you should be able to do something like: 

```rust
fn layout(&self, info: &LayoutInfo<T>) -> Dom<T> {
     Dom::image(ImageSource::Path("../my_image.jpg"))
}
```

... and have the framework do the caching / loading, etc. work for you. But this will take some time to implement, hopefully not too long.

To your last question, that example seems to be out of date. `ImageType::Jpeg` is not necessary anymore because the framework will guess the image type automatically (depending on the header of the image). Just remove the parameter. For some reason CI didn't catch this, thanks for reporting.

**Comment by dondreytaylor** [comment]
Ahhh totally missed importing the `image_loading` feature. Okay, I see now how to reference the image using Dom:image, thanks for the explanation.
