### ISSUE TITLE
[Feature Request] Allow error-propagation

### ISSUE THREAD

**Issue by Xoronic** [maps4print/azul#13]
## Description

I tried to propagate errors instead of letting the program `panic!` with `unwrap()` calls:

```rust
fn start() -> Result<(), /* What to put here? */> {
    // Instantiate the app with default values.
    let mut app = App::new(DataModel::default(), AppConfig::default());

    // Create a new window.
    app.create_window(WindowCreateOptions::default(), Css::native())?;

    // Run the app.
    app.run()?
}
```

The example above illustrates the issue: 
- **`app.create_window`** returns a `Result<(), WindowCreateError>`
- **`app.run`** returns a `Result<T, RuntimeError<T>>`

But they do not share an `Into` (or `From`) implementation. In other words: There is a lack of an Error-implementation higher in the hierarchy.

This forces the API-consumer to either `unwrap` all errors which:
- Causes visual clutter in the code
- Panics: Exactly the thing that the `Error` type should prevent

### Option 1: Implement `std::error::Error` for all the top-level error-types in Azul
From looking at the code, that would be:
- `CssParseError`
- `FontError`
- `ImageError`
- `ClipboardError`
- `WindowCreateError`

I'm not sure, but I think that those are the only errors returned from functions in the library.

### Option 2: Create one top-level `azul::Error`
The `azul::Error` should then be implemented by all the errors mentioned in *option 1*.

Which all other azul Errors can convert into. (Also see [rfc-356](https://doc.rust-lang.org/1.0.0/style/style/naming/README.html#avoid-redundant-prefixes-[rfc-356]) about stuttering names)

### Option 3: Kind-of combination of option 1 and option 2
Creating one top-level `azul::Error` which implements `std::error::Error`. This allows API-consumers to use the azul::Error together with other libraries and use the errors interchangeably.

This one is my favourite :)

## Is this a breaking change
I'm not sure,  option 2 and 3 may be be a breaking change?

__________________

I'm willing to help and write the code if you find one of the solutions a good idea.

Great job by the way, I like the library and I think it has a big potential of becoming a widely used GUI library for Rust (which is something Rust really needs).

**Comment by fschutt** [comment]
Yeah, I'd go with option 3, a global error enum, I'd put it in a seperate `error.rs` file. I'm currently working on the documentation, I'll take a look later. Breaking changes aren't a problem, this library isn't even on crates.io yet, nobody should expect this library to be anywhere near stable.

**Comment by Xoronic** [comment]
Hmm, this involves more work than I initially expected. The error must implement `fn cause()` and `fn fmt()`. If you want the error to be at least a bit meaningful, `fmt` should print the underlying error and `cause`return it as a cause. That would require *all* errors in the library to implement `std::error::Error` and `std::fmt::Debug`.. Right?

What are your thoughts about this?

Maybe it is worth implementing the [failure](https://github.com/rust-lang-nursery/failure) library? It looks pretty cool :) Never used it though..

**Comment by fschutt** [comment]
Do not use failure. Azul already has 113 dependencies and failure hugely overcomplicates things for no reason. Failure is mainly a convenience library for **quick CLI applications** and has [huge performance problems](https://www.reddit.com/r/rust/comments/7te8si/personal_experience_can_cause_hard_to_notice/). Failure is overengineered to the extreme and in this case it's absolutely unnecessary.

Don't implement `std::error::Error` - I should have said this earlier. In my opinion, `std::error::Error` is the most useless trait in the whole standard library because `.cause()` can only return a `&str`, not a `String`, so you can't return dynamic error information without jumping through hoops (which nobody does, so everybody just returns a `&static str` and leaves the error information out, which is not the point of printing an error). The `.cause()` method also is often completely unnecessary, because the information conveyed in the `Error` returned by `.cause()` is already conveyed by `std::fmt::Debug` or `std::fmt::Display`. The only thing you can do with the `Error` object returned from `.cause()` is to print its `.description()` - but that's already what the `Debug` and `Display` traits do! Plus it now limits every error to only return a `&str`, so you can't put dynamic formatting in your error printing, as above.

So there is absolutely nothing gained by implementing `std::error::Error`, it's purely boilerplate noise that nobody needs. It's just something that many people do because "it's in the standard library, so it must be good to implement". Most people only use `std::error::Error` to print the error - but `Display` and `Debug` are much more flexible (because they can dynamically format an error).

`std::error::Error` also makes other problems, such as having error information duplicated between `Display` and `Error`, requiring an impl for all sub-types, which again, leads to more boilerplate noise as you've already experienced - or overengineered solutions such as failure or error-chain.

Another reason to not do it is that this is a GUI library and I don't expect anyone to wrap his errors in any sub-functions. If a user wants to create an error, he has to put these errors in his data model (callbacks aren't allowed to return an error) - if the user then wants to implement `std::error::Error` for them, that's fine by me, but that's not the concern of this library.

Lastly, remember that the only reason why you wanted to implement this is that you can do `fn main() -> Result<(), azul::Error>` - that doesn't require you to implement `std::error::Error` for `azul::Error`, only `std::fmt::Debug`: https://play.rust-lang.org/?gist=edd6d6dc2f5ebe2a5ff12a58b7fee3a6&version=stable&mode=debug&edition=2015

So just make a wrapper error enum, implement `std::fmt::Debug` and/or `std::fmt::Display` on it and leave `std::error::Error` out. It's neither necessary nor a particularly useful trait to implement.

**Comment by Xoronic** [comment]
Thanks for your thorough reply! I'm still going to try and defend `std::error::Error` though :)

## Failure crate
> Do not use failure. Azul already has 113 dependencies and failure hugely overcomplicates things for no reason. Failure is mainly a convenience library for quick CLI applications and has huge performance problems. Failure is overengineered to the extreme and in this case it's absolutely unnecessary.

I did not know about those performance problems and I agree that that is unacceptable. Let's not use failure then :)

## std::error::Error
> Don't implement std::error::Error - I should have said this earlier. In my opinion, std::error::Error is the most useless trait in the whole standard library because .cause() can only return a &str, not a String, so you can't return dynamic error information without jumping through hoops (which nobody does, so everybody just returns a &static str and leaves the error information out, which is not the point of printing an error). The .cause() method also is often completely unnecessary, because the information conveyed in the Error returned by .cause() is already conveyed by std::fmt::Debug or std::fmt::Display. The only thing you can do with the Error object returned from .cause() is to print its .description() - but that's already what the Debug and Display traits do! Plus it now limits every error to only return a &str, so you can't put dynamic formatting in your error printing, as above.

I'm getting the feeling that you had some bad experiences with the `std::error::Error` trait in the past. It has changed a bit, though.

This is the current Error trait (taken directly from the standard library):

```rust
pub trait Error: Debug + Display {
    fn description(&self) -> &str;
    fn cause(&self) -> Option<&Error>;
}
```
Description returns a `&str`. Cause optionally returns the underlying cause.

Description is soft-deprecated: [rfc 2230-bury-description](https://github.com/rust-lang/rfcs/blob/master/text/2230-bury-description.md). The docs state:

> Although using it won’t cause compilation warning, new code should use Display instead and new impls can omit it.

(Notice that Error also requires a `Display` implementation)

### Why implementing it?
> So there is absolutely nothing gained by implementing std::error::Error, it's purely boilerplate noise that nobody needs. It's just something that many people do because "it's in the standard library, so it must be good to implement".

The reason I created this feature request is error-propagation :).

> Lastly, remember that the only reason why you wanted to implement this is that you can do fn main() -> Result<(), azul::Error> - that doesn't require you to implement std::error::Error for azul::Error, only std::fmt::Debug

An example of what annoys me about libraries that do not implement `std::error::Error` for their types:
```rust
extern crate foolib;
extern crate barlib;

fn my_function() -> Result<(), Box<std::error::Error>> {
    let foo = foolib::Foo::new()?;
    let bar = barlib::Bar::new()?;
}
```

And that's a problem because we've got a problem because `barlib` does not implement `std::error::Error` on it's error-types...

[The same example but *with* an std::error::Error implementation](https://play.rust-lang.org/?gist=6e43076bfcad555e765581b1048605b3&version=stable&mode=debug&edition=2015)

You might say about that code that a heap-allocated error is a performance-issue. IMHO though, an error should be an exception, it should not happen often. It should not be the rule.

### Only implementing `Display`
> So just make a wrapper error enum, implement std::fmt::Debug and/or std::fmt::Display on it and leave std::error::Error out. It's neither necessary nor a particularly useful trait to implement.

The difference between implementing `Display` and implementing `Display` *and*  `std::error::Error` is **one line**:

```rust
impl error::Error for Error {}
```

**Comment by fschutt** [comment]
Okay, let me prefix this with the admission that I didn't know that `std::error::Error` allows an empty implementation, but I still think it's a bad idea, esp. for azul:

- Description is soft-deprecated and the docs want you to use `Display` instead - this just reinforces what I said earlier: the `.description()` (and therefore the whole trait) is pretty useless - even the Rust core team has now (finally) acknowledged this. 
- Returning `Box<Error>` from a function **is an anti-pattern and should not be done**. Please don't do this in your code - the reason isn't even performance, the reason is that you just **erased all the type safety** that Rust enums give you - because of laziness or "convenience". If you look at a function that returns `Box<Error>` in three months - how do you know which exact error this function could return without reading through the source code? Exactly, you can't. So: eat your spinach and do it properly:

```rust
extern crate foolib;
extern crate barlib;

enum MyFunctionError {
    FooLibError(foolib::Error),
    BarLibError(barlib::Error),
}

fn my_function() -> Result<(), MyFunctionError> {
    let foo = foolib::Foo::new().map_err(MyFunctionError::FooLibError)?;
    let bar = barlib::Bar::new().map_err(MyFunctionError::BarLibError)?;
}
```

Your future self will thank you because when you inevitably need to refactor this piece of code - now you know that `my_function` can *only* fail in two ways - either with a `FooLibError` or a `BarLibError`. If you had used `Box<Error>`, then you don't know how this function could fail - there could be two error cases or a hundred, you don't know it, becaused you erased the type.

I've also noticed that implementing `Error` leads to very bad code style - I've even seen people casting strings as `Box<Error>`, like this:

```rust
fn something() -> Result<(), Box<Error>> {
    return Box::new(io::Error::Other("something went wrong".to_string()));
}
```

This code above isn't proper error handling, it's bullshit (or simply laziness). It carries zero type information about the error and I simply want to discourage that kind of coding, because it's a horror to work with - both as a user of a library and as a maintainer. Also, should you ever wish to localize (translate) your error messages - with enums you can, with `Box<Error>` - good luck.

Essentially, returning `Box<Error>` throws out everything that is great about the Rust error handling mechanism and returns to C++-style exceptions, where you can only catch the exception, call `e->what()`, but you can't do much else because you don't know what kind of error exactly was returned or what data / extra information the error carried. Implementing `std::error::Error` encourages such code style, which is why I regard it as bad, and yes, I don't think that your "error propagation" technique is something you should do.

Lastly:

- If you really wanted to, you can still implement `std::error::Error` for the `MyFunctionError`, without the need to modify `foolib` or `barlib`. As long as `foolib::Error` and `barlib::Error` implement `Display` and `Debug` (which I'm not opposed to), you can wrap the error type and implement `Error` for that wrapped type if you really want to.
- In Rust, `Error` is returned pretty often, `panic!` is what you should avoid. You can quickly run into a situation where you execute a function in a loop and filter by `.is_err()` or `.is_ok()` - imagine you iterate over a million items and every function call returns a `Box<Error>` - this is where the performance problems start.

Yes, I realize that it's just one line, but it's a useless line that leads people towards writing pretty bad code. The main experience with this was the postgres crate, by the way. They do exactly this, return a `Box<Any + Error>` (which, internally is a string, not even a properly typed enum) and I wanted to recover on a very specific PostgreSQL error, i.e. `if let PostgresError::Io(IoError::ConnectionFailed(_)) { }`- but couldn't do that because hey let's all use `Box<Error>`, right?

So my suggestion is to just implement Debug + Display on an `azul::Error` enum. Also, as I said, the only place where errors are returned is in the main function - callbacks are not allowed to return errors, in order to show errors to the user, you have to either move them into the data model or directly show a message box prompt. azul isn't made to be wrapped inside another library, it's not an "upstream" library like an XML parser that people build other libraries on top of, the output is directly a binary, so returning `Box<Error>` just to immediately return it from the main function makes little sense. 

I'm sorry but I don't see a reason why `std::error::Error` is needed. But you are still welcome to help implementing Display - writing nice error messages and refactoring the errors is a good starting point - that'll be the main work anyways - we can still discuss the viability of implementing `Error` after that's done, implementing `Error` isn't a big task if the `Debug` + `Display` are implemented.

**Comment by anderejd** [comment]
> If you look at a function that returns Box<Error> in three months - how do you know which exact error this function could return without reading through the source code? Exactly, you can't. So: eat your spinach and do it properly

😆 

Would you mind if I nominate this for quote of the week?

**Comment by ErichDonGubler** [comment]
@fschutt: would you be open to simplifying implementation of implementing `Display` with something like [`display_derive`](https://github.com/withoutboats/display_derive)?

**Comment by Xoronic** [comment]
@fschutt Thanks, you convinced me! I learned a lot :)


> But you are still welcome to help implementing Display - writing nice error messages and refactoring the errors is a good starting point

I will do that

> So my suggestion is to just implement Debug + Display on an azul::Error enum

So all functions in the library that return a Result should have an error type that can be converted to an `azul::Error`, right?

**Comment by fschutt** [comment]
> Are there any cases where an `std::error::Error` is useful then?

I have never needed `std::error::Error` - there isn't a case where you couldn't use `Debug` or `Display`, and if you are presenting errors to the user, you need to incorporate factors such as localization anyway, at which point error enums are far more useful than `.description()` and `.cause()` - because there is a very likely case that you'll want to format error strings to your liking. The only reason I can think of is because it has a nicer way of printing the underlying cause of the error recursively, but if you need that level of customization in your error messages, it's may be better to go DIY.

As for `display_derive`... I don't want to sound like I don't accept any external crates, but `display_derive` spares you 5 lines of code per `impl` block and decreases the readability with things such as `_0` (which refers to `self.0`, but you'd have to know that). It is purely syntax sugar, but the cost are 5 extra dependencies which azul doesn't have yet:

```
├── quote v0.3.15
├── syn v0.11.11
│   ├── synom v0.11.3
│   │   └── unicode-xid v0.0.4
└── synstructure v0.6.1
```
Also notice that these dependencies are quite outdated, quote is at 0.6.6, unicode-xid is at 0.1, it doesn't seem like these dependencies are updated very frequently (or ever).

Since errors are necessary to use azul and can't go behind a feature flag (like with `serde`, which is optional in azul and is not included by default due to the additional dependencies), this would bring in 5 extra dependencies to spare writing 5 lines of code per error type, that means for the 4 error types azul has, 20 lines total spared. Now, is it worth it to include 5 dependencies to spare writing 20 lines of code? I don't think so, but if you are concerned about the unnecessary LOC: Here is a macro that does the same as `display_derive`, but in 15 lines:

https://play.rust-lang.org/?gist=17212d78f6eb69e61e6f0b65ac2ca49d&version=stable&mode=debug&edition=2015

No dependencies, no syntax changes like `_0`, no custom derive needed. Sometimes you just need to keep it simple.

**Comment by Xoronic** [comment]
This what I did so far:

https://github.com/Xoronic/azul/tree/errors

I created a quick example (which will be removed before any pull request) of the output of some printed errors:
https://github.com/Xoronic/azul/blob/errors/examples/errors.rs

**Comment by Xoronic** [comment]
I intentionally did not include `RuntimeError` in the `Error` struct, for two reasons:

- It is near impossible to do so because of the generics
- If that function fails you probably don't want to propagate that error anyway

**Comment by fschutt** [comment]
@Xoronic There is an `impl_from` macro already: 

https://github.com/Xoronic/azul/blob/c561d6129d84a7259499135f0390c7836e91965a/src/css_parser.rs#L27-L47

and here it the usage: 

https://github.com/Xoronic/azul/blob/c561d6129d84a7259499135f0390c7836e91965a/src/css_parser.rs#L127-L157

Also, it would maybe be cool if you put the macros in a separate `macros.rs` file (just grep for `macro_rules!` and put them in a seperate file) - but be aware that you have to use `#[macro_use] mod macros` in the lib.rs file before any other modules (macros have to be defined before being used).

And you can then change the debug print to a display print here: https://github.com/Xoronic/azul/blob/errors/src/css.rs#L224 - so that people get the proper, nicely formatted error instead of the debug information during hot-reloading.

You also don't need to create an extra error example, the existence of `Display` on the error type is enough. And yeah, the problem with `RuntimeError` is that it contains a `MutexPoisonError<T>` and I don't want to restrict `T: Debug` or `T: Display` just because of an error.

**Comment by Xoronic** [comment]
Speaking of tests, there were some tests that failed. I'm not sure if that's only in my branch or  if they failed in the master-branch as well..

**Comment by fschutt** [comment]
Master branch is green, so I'm not aware of any tests failing. But redo the macro name: The regular macro should be `macro_name` and the macro with lifetimes should be `macro_name_with_lifetimes`. I got that reversed in my `impl_from` macro, it would be nice to revert that (just change the macro names around).

**Comment by Xoronic** [comment]
Please check my latest push to my fork: https://github.com/Xoronic/azul/commit/229931bd16e1b5c2d378021a6232d8530e5df3a9

**Comment by Xoronic** [comment]
I created an issue for the failed test. It also occurs in the master-branch: #16

**Comment by fschutt** [comment]
Looks good for now, the rest can be discussed in a PR. Thanks for working on this.
