### ISSUE TITLE
Panic when running on Server 2012 R2 via RDP session

### ISSUE THREAD

**Issue by Malfeasant** [maps4print/azul#132]
## Description

Built/ran the Hello World example- received a panic, the meat of it seems to be:
CreateError(NoAvailablePixelFormat)
I copied the executable from the remote machine where my build environment resides to my local (Windows 10) machine, and it ran without error.  I'm not positive if RDP is the problem, or Server 2012 R2.

## Version / OS

* azul version:
version = "0.1.0"
source = "git+https://github.com/maps4print/azul#809cc3cf4a2ca163d6826ee017be72d1f1be8d9b"

* Operating system:
Windows Server 2012 R2 Standard

* Windowing system (X11 or Wayland, Linux only):

## Steps to Reproduce

Build & run the Hello World application (or likely any which produce a window)

## Additional Information

![image](https://user-images.githubusercontent.com/1212508/55264177-c2b41380-5230-11e9-9cc0-d7c1cdf61f26.png)
[error.log](https://github.com/maps4print/azul/files/3024637/error.log)

**Comment by fschutt** [comment]
The error means that glutin couldn't establish an OpenGL context, because you have to have at least OpenGL 3.2 installed (and Windows Server only comes with OGL 1.0 if I'm correct). It technically should fall back to software rendering, but I'm afraid that's not correctly implemented. You probably need to install graphics drivers on the Windows Server (usually Intel HD drivers if it's a pure virtual machine).

**Comment by Malfeasant** [comment]
It appears you're right.  I experimented further (remoted from another machine to the windows 10 machine where the program worked) and it still works through rdp, so it's not that.  The Server 2012 box is a physical machine, not a vm for what it's worth, It's just not one I have physical access to.  It has AMD Radeon HD 8670D graphics - I ran an OpenGL/DirectX test which reported an OpenGL version of 1.1.  I installed the Radeon drivers, but it made no difference.  There seem to be a few articles about this exact problem, so I have some reading to do.

**Comment by fschutt** [comment]
You could run the program in debug mode, which should at least give you a stack trace as to where the program is crashing - right now it's just printing "unresolved function" because there is no debug information available for a stack trace.

**Comment by Malfeasant** [comment]
Let's go ahead and close this.  I notice there is another issue relating to insufficient OpenGL version, and that's most likely what the issue is here.

**Comment by niklasha** [comment]
I am not sure that it is not RDP-related.  Given this excellent post: https://stackoverflow.com/questions/51705471/current-state-and-solutions-for-opengl-over-windows-remote
it seems RDP sessions can not *setup* windows requiring OpenGL > 1.1, but it can still *connect* to sessions with such windows already created.  Anyway, my question is: is there any plan to get the fallback to software rendering to work?  Using RDP (without tricks like running batch jobs that disconnect/start our applications) is pretty much a show-stopper for the environment I am tartgetting.  I am not afraid of looking into helping out, but although a rather experienced developer (like 40 years of hacking :-) ), I am not very experienced with Windows subtleties, nor OpenGL at all.  Not that I cannot learn, but if there is anyone better suited already having this in their pipe, I rather see that happening.  Otherwise a pointer to where in the stack the fallback is supposed to happen would be nice.  Can you provide that @fschutt ?

**Comment by fschutt** [comment]
@niklasha I've made a bit of progress including a `OSMesaContext` here: https://github.com/maps4print/azul/commit/62194aef44a8d57d3d009868255963a0faf8214c

But first I'll have to fix all the other problems, software rendering is very low on my priority list. Software OpenGL basically just means implementing the `Gl` trait for `OSMesaContext` and then implementing the logic to fall back on OSMesa on startup [here](https://github.com/maps4print/azul/blob/dcc69cd12acc77676ce2228064395228d17eac93/azul/window.rs#L794-L795) and [here](https://github.com/maps4print/azul/blob/dcc69cd12acc77676ce2228064395228d17eac93/azul/window.rs#L807-L826) - instead of loading the GL function pointers from the system in `create_headless_context()`, it should load them from the GL context - and allocate / deallocate video memory on resizing events. That should be enough so you can get software OpenGL working.

Later on you might want to translate a `CachedDisplayList` into pixels without going through software OpenGL for optimizing azul for embedded devices, but that's simply not the goal right now. It's possible to build an `azul-embedded` crate later on, but it's not a priority.

I've also learned that linking OSMesa statically is a very bad idea since building it statically takes minutes to hours. It could still be an option (for release builds), but not recommended for debug builds.
