### ISSUE TITLE
Webrender GFX-rs branch

### ISSUE THREAD

**Issue by skyne98** [maps4print/azul#135]
## Description
Hey there, [there is a branch](https://github.com/szeged/webrender) of webrender, where people are working on its GFX-rs port. I wonder if it is possible to add a feature to Azul, allowing to use this backend?

My motivation behind this is having a nice UI framework for systems where GFX-hal is used as a overall graphics layer.

## Describe your solution
Both versions of Webrender should be compatible with each other, so just import one instead of another and solve some dependency conflicts.

## Are there alternatives or drawbacks?
Current state of GFX-rs WebRender is far from finished, however, they are doing a great job and it looks usable at the moment.

## Is this a breaking change
Shouldn't be any.

**Comment by fschutt** [comment]
See https://github.com/servo/webrender/issues/3453#issuecomment-450504131

It will likely not be implemented, because the benefits are too small compared to how much effort it is. It's not possible to just "change the backend", because that still wouldn't make it possible to integrate Azul into a gfx-rs application, which I suppose is the real goal here.

> My motivation behind this is having a nice UI framework for systems where GFX-hal is used as a overall graphics layer.

Yes, but that's not really a reason to change the rendering backend. If there were significant performance benefits or there would be constant bugs with OpenGL then that would be more of a reason to switch, but rendering performance is the least of Azuls performance problems. So changing from OpenGL to gfx-rs just "because it's gfx-rs" is not really a good enough motivation.

Instead, it should be possible to integrate Azul into an existing appliction. Right now Azul can already render to an OpenGL texture, so that's a starting point. The goal is to embed the rendered OpenGL texture, rather than to change the entire backend, but this will probably need an API break in order to work.

The problem is more that Azul currently owns the event loop, so there is currently no way to "embed" an Azul UI into an existing windowing framework, for example SDL2. The solution I've thought about is more or less to allow the framework to send messages to the Azul UI thread and ask for the rendered UI in the form of a texture. That way it should be able to integrate Azuls OpenGl rendering with gfx-rs, Vulkan and DirectX (via OpenGL embedding extensions). However, webrenders gfx-rs is fairly unstable, the progress on the Vulkan branch is very slow and also not maintained by Mozilla, so there is little commercial effort or need behind it - don't hold your breath that it will ever reach production quality. So my position is "would be nice to have, but too much effort for very little gain".

**Comment by skyne98** [comment]
@fschutt, thanks for your detailed response! You might be right saying that my intentions are more or less "just because it is gfx-hal". With each day I am starting to understand more and more that there are no real drawbacks to using OpenGL (especially the latest ones) in user interfaces compared to Vulkan or Metal.

However, I have another question: what do you think about using Azul as a base for a Smithay (Wayland) based compositor? My understanding is that, first of all, webrender will have to implement Smithay's GL backend. Secondly, webrender or azul will have to learn to render textures themselves.

Thanks!

**Comment by fschutt** [comment]
> What do you think about using Azul as a base for a Smithay (Wayland) based compositor?

I don't know much about Wayland, but I did manage to write a proof-of-concept X11 compositor using glium and OpenGL (it just shows a red screen after you log in). A compositor is just a regular desktop application that runs in fullscreen mode. So it shouldn't be too difficult - all you need to do is to get the rendered output from the applications, create an OpenGL texture and then you can take those textures and add them into the DOM like an image and apply effects to them. Right now I'd say Azul is currently a bit too unstable (both in API and in terms of bugs) to use it in a window compositor, but that depends on your needs.

> Webrender or azul will have to learn to render textures themselves.

WebRender only renders to the "currently active" surface, i.e. WR doesn't care whether you draw to a screen or to a texture. Azul on the other hand shares the main renderer across OS-level windows, which is why it [draws the UI to a texture first](https://github.com/maps4print/azul/blob/87f3fb2dfd5c3976a284ebb06c8ced6217e0950b/azul/src/app.rs#L1204) and then to the respective screen. In other words, Azul is already drawing the UI to a texture (since that is necessary for apps with more than one window), so it's just a matter of "What API is necessary to allow users to embed this rendered texture in their applications?".

**Comment by skyne98** [comment]
>I don't know much about Wayland

[Smithay](https://github.com/Smithay/smithay) is a rust project that aims to create a platform for wayland compositors written in rust. It looks very promising and seems to be supported by a couple of major rust projects (they have smithay-client as a dependency).
The point is that smithay already has an implementation of EGL based on DRI, that allows them to use glium(?) to draw their interface.

The question is whether it is possible to add it as a backend for azul. We have previously talked with one of the maintaintes about adding smithay as an alternative OpenGL backend for GFX-rs, therefore it it should mean that it can potentially be used as a backend for other OpenGL bindings. Also, yeah, compositor is just a fullscreen application, however, it has to create an OpenGL context in a very specific way and in that case Smithay is very useful.

>WR doesn't care whether you draw to a screen or to a texture.

The problem is different. To create a compositor you need it to receive texture from OpenGL and Vulkan instances and compose them together. For that, you need some way of representing those "foreign" textures in the program and rendering them.

**Comment by fschutt** [comment]
Well, does WebRender run on the Smithay backend? My guess is no, then there's no way to run Azul on it. Plus, I have to say, you are essentially re-implementing OpenGL interfaces using DRI, that's not what webrender was made for. 

For example, how would you create a GPU-accelerated blur effect using DRI? For this, you'd need to emulate shaders - this isn't what webrender or Azul were made for. WR relies on these kinds of effects to be present in your implementation of OpenGL, but emulating them is probably way beyond the capabilities of Azul and webrender. Azul can render to an OpenGL texture and can take other OpenGL textures and compose them, that's about it. I doubt that re-implementing webrender on DRI is a good idea or that you can adapt / port WR to run on DRI, because WR needs a lot of capabilities of OpenGL 3.3, you'd have to essentially re-implement the entire API surface. Try getting a WebRender example to run as a Wayland compositor, then we can talk about how to adapt Azul to fit that use-case.

**Comment by skyne98** [comment]
@fschutt, no-no, you are not re-implementing OpenGL interfaces, you are actually using Wayland extensions to create OpenGL contexts and then use them directly. Maybe I don't understand something, but that doesn't sound like re-implementing interfaces.
So, once there is a capable branch of webrender, it can be used as a backend?

**Comment by fschutt** [comment]
> So, once there is a capable branch of webrender, it can be used as a backend?

Well, the Vulkan branch is several hundred commits behind servo:master, so there might be a few API changes necessary. Other than that - I don't know, maybe. I'm really not an expert in Wayland, you'll just have to experiment and try it out.
