### ISSUE TITLE
Overflowing text in input field is displayed higher than non-overflowing.

### ISSUE THREAD

**Issue by mjhouse** [maps4print/azul#142]
## Description
Text line positions in an overflowing text input are different from non-overflowing.

## Version / OS
* azul version: 1eef92224e93a05ad584b88f671effa382afc7e2
* Operating system: Windows

## Steps to Reproduce
* run the text_input example
* type into the text field until the field overflows
* notice that when the text overflows, all visible text is rendered a few pixels higher.

## Additional Information

![image](https://user-images.githubusercontent.com/4141157/55735988-16b8b800-59e8-11e9-981b-d68c4f74fb14.png)

![image](https://user-images.githubusercontent.com/4141157/55736054-3354f000-59e8-11e9-9802-783231c7e4b4.png)

Notice the spacing between the border of the text field and the top of the text in the above images.

**Comment by fschutt** [comment]
This is fixed (font is still a bit small, but it's fixed).

![image](https://user-images.githubusercontent.com/12084016/59760183-fe8bd180-9291-11e9-9ed1-e37f230696de.png)

It happened because I tried to be "smart" and only center text when it's not overflowing the parent. Now it's consistent, and the text position (if it overflows) should be fixed via scrolling.
