### ISSUE TITLE
Examples don't show correctly on linux

### ISSUE THREAD

**Issue by LeonGGX** [maps4print/azul#15]
On ubuntu 18.04 with Gnome and X11, the examples don't show correctly (buttons are invisible, svg images don't show the way they should appear, the table demo shows nothing.)
I get the following message : "_GtkDialog mapped without a transient parent. This is discouraged."_, but I'm not sure this is the real cause of the problem ...
Thanks anyway for the great job, azul seems very promising.

**Comment by fschutt** [comment]
Could you provide screenshots of what the problems are? Currently:

- The table demo shows nothing, but should print something on the screen. Sub-DOM rendering is pretty hard and doesn't work yet.
- The async example should show a button and a label that you can click on, which starts a background task that does nothing and counts up to 10 seconds in the main thread - showcasing how tasks and daemons work
- The debug example should allow you to open an SVG file, yes I know that the tiger is distorted right now, but it should at least draw the tiger and a few rectangles on to and allow you to zoom in / out by using ctrl + scroll and panning on the tiger with shift + scroll.
- The hot reload example should roughly show you the WIP image in the README and respond to edits in the hot_reload.css file 
- The test_input example should show a rectangle across the top of the screen. Right now there is a bug in the text layout, hover your mouse over the rectangle and press enter to show the message. This is supposed to demonstrate self-updating fields / two-way data binding. The problem is with the text layout however, not with the updating itself.

**Comment by LeonGGX** [comment]
Here are the screenshots of a few examples.
The table demo indeed prints something in the console.
The debug example doesn't show any button in the upper left corner (but it does in Windows 10).
The test_input example only shows a line (or is it the lower part of the text input ?) at the top of the window.
Anyway, I'm eager to see the finished product, this is great job.

![azul-debug](https://user-images.githubusercontent.com/37880486/45481840-1ac77480-b73c-11e8-998b-c08908067e4b.png)
![azul-table_demo](https://user-images.githubusercontent.com/37880486/45481852-2155ec00-b73c-11e8-9800-163190adc23b.png)
![azul-test_input_field](https://user-images.githubusercontent.com/37880486/45481860-25820980-b73c-11e8-8328-030a71c8560f.png)
