### ISSUE TITLE
how to do OpenGL rendering?

### ISSUE THREAD

**Issue by JAicewizard** [maps4print/azul#157]
I am trying to start drawing using OpenGL, but it is not very well documented. 
after I figured out how to get a Facade for shader compilation, I got stuck on trying to get the glium macro's to work (that's what they do in their examples). I'm new to rust and am not sure how to get my first triangle on the screen.
Would it be possible to have a simple triangle example besides just a background colour?

**Comment by fschutt** [comment]
> I got stuck on trying to get the glium macro's to work

If you are on macOS, glium currently doesn't work due to #131. What exact problems do you have with the glium macros (code / error message)?

Once you have a framebuffer, you can upload your vertices to the GPU with `VertexBuffer::new()` / `IndexBuffer::new()`, use the [SVG code](https://github.com/maps4print/azul/blob/9090ce23a114222fcc08dc76b35381e671ab80e7/azul/src/widgets/svg.rs#L2047-L2053) as an example. However, teaching how to use OpenGL in detail is out of the scope of the wiki, it's just supposed to show how to get access to the OpenGL context - see https://learnopengl.com/ for more information.

**Comment by JAicewizard** [comment]
the glium [`example`](https://github.com/glium/glium/blob/master/book/tuto-02-triangle.md) uses `implement_vertex!(Vertex, position);`, but I cant get this glium macro to get imported properly. I don't expect a full tutorial which is why I tried to follow the glium examples, but I would like to be able to follow other resources.

I guess a solution would be to _also_ import glium separately and use that. but I am not 100% sure if that's appropriate

**Comment by fschutt** [comment]
I am currently reworking the OpenGL code to rely less on glium (see the /gl_rework branch). So either wait a few days or (alternatively) you can import the `implement_vertex!` macro from `azul-dependencies`, i.e.:

```toml
[dependencies]
azul-dependencies = { git = "https://github.com/maps4print/azul-dependencies", rev = "380b7e7cba8b728a3fc89fe28952e3b07aa624e7" }
```

```rust
#[macro_use(implement_vertex)]
extern crate azul_dependencies;

struct Vertex { a: usize }

implement_vertex!(Vertex, a);
```

**Comment by JAicewizard** [comment]
Thanks!
As I love doing too much I will definitely do this now, ans then update everything when everything works :)
I think this can be closed now, unless you still want to keep this open

**Comment by JAicewizard** [comment]
Thanks!
As I love doing too much I will definitely do this now, ans then update everything when everything works :)
I think this can be closed now, unless you still want to keep this open
