### ISSUE TITLE
Doc-tests fails in master-branch

### ISSUE THREAD

**Issue by Xoronic** [maps4print/azul#16]
## Description
```
   Doc-tests azul

running 8 tests
test src/app.rs - app::App<T>::run (line 176) ... ignored
test src/app_state.rs - app_state::AppState::windows (line 32) ... ignored
test src/css.rs - css::DynamicCssProperty (line 145) ... ignored
test src/default_callbacks.rs - default_callbacks::stack_checked_pointer::is_subtype_of (line 135) ... ignored
test src/window.rs - window::Window::marker (line 498) ... ignored
test src/window.rs - window::Window::marker (line 504) ... ignored
test src/app.rs - app::App<T>::delete_font (line 430) ... FAILED
test src/app_state.rs - app_state::AppState<T>::add_font (line 132) ... ok

failures:

---- src/app.rs - app::App<T>::delete_font (line 430) stdout ----
error[E0599]: no method named `mock_render_frame` found for type `azul::prelude::App<MyAppData>` in the current scope
  --> src/app.rs:447:5
   |
19 | app.mock_render_frame();
   |     ^^^^^^^^^^^^^^^^^

thread 'src/app.rs - app::App<T>::delete_font (line 430)' panicked at 'couldn't compile the test', librustdoc/test.rs:330:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    src/app.rs - app::App<T>::delete_font (line 430)

test result: FAILED. 1 passed; 1 failed; 6 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--doc'
```

## Version / OS

* azul version:
Version 0.1.0

* Operating system:
Linux 4.15.0-34-generic x86_64  (Ubuntu 18.04.1)

* Windowing system (X11 or Wayland, Linux only):
X11

## Steps to Reproduce

Run `cargo test` in the project directory.

## Additional Information
```
$ rustup toolchain list
stable-x86_64-unknown-linux-gnu (default)

$ cargo --version
cargo 1.28.0 (96a2c7d16 2018-07-13)

$ rustc --version
rustc 1.28.0 (9634041f0 2018-07-30)
```

**Comment by fschutt** [comment]
Oh you meant that... I'm closing it for now because this isn't a bug - run it with:

```
cargo test --features "doc-test no-opengl-tests"
```

and it should pass. The reason for this is that we can't use OpenGL or any windowing system on travis or appveyor, as they are "headless" systems and don't have X11 installed. Hence the features flags. I originally wanted this to run reftests, but this is more complicated. I asked the servo maintainers about this, they have a solution involving OSMesa, but this is quite complicated to set up.

All that test is doing is checking that you can upload a font, and that it's in the "uploaded" stage after the next draw call. So it's currently impossible to fix that, hence the feature flags.

**Comment by fschutt** [comment]
IRC log from when I asked about this, just for context: 

\<gw\>:  fschutt: It should work on any existing CI platform so long as you can compile OSMesa (it just has a couple tricky dependencies like llvm).  This is the servo code to set up the OSMesa context - https://github.com/servo/servo/blob/ce430566cdbccaa86ec498aa48392eab3ec69256/ports/servo/glutin_app/window.rs#L81, and the CI script to ensure that the OSMesa libs are in the correct lib loading path https://github.com/servo/servo/blob/1f9b07637ea960f6b3d4004f832951ad9b6b48ed/python/servo/command_base.py#L194
