### ISSUE TITLE
Panic running debug example on mac

### ISSUE THREAD

**Issue by adamski** [maps4print/azul#18]
I get a panic running the debug example. Rust 1.29.2, macOS 10.12.6

```
[ERROR][azul::logging] We are sorry, an unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: libcore/option.rs at line 345 in thread main

Error information:
called `Option::unwrap()` on a `None` value

Backtrace:

backtrace::backtrace::trace @ mod.rs:42
backtrace::capture::Backtrace::new_unresolved @ capture.rs:88
backtrace::capture::Backtrace::new @ capture.rs:63
azul::logging::set_up_panic_hooks::panic_fn @ logging.rs:84
core::ops::function::Fn::call @ function.rs:73
std::panicking::rust_panic_with_hook @ panicking.rs:479
std::panicking::continue_panic_fmt @ panicking.rs:390
 @ panicking.rs:325
core::panicking::panic_fmt @ panicking.rs:77
core::panicking::panic @ panicking.rs:52
<core::option::Option<T>>::unwrap @ macros.rs:20
debug::my_button_click_handler @ debug.rs:150
azul::app::do_hit_test_and_call_callbacks::{{closure}} @ app.rs:723
azul::app::do_hit_test_and_call_callbacks @ app.rs:735
<azul::app::App<T>>::run_inner @ app.rs:234
<azul::app::App<T>>::run @ app.rs:192
debug::main @ debug.rs:235
std::rt::lang_start::{{closure}} @ rt.rs:74
std::panicking::try::do_call @ panicking.rs:310
 @ lib.rs:105
std::rt::lang_start_internal @ panicking.rs:289
std::rt::lang_start @ rt.rs:74

```

**Comment by fschutt** [comment]
Yeah I know about this, but I sadly don't have a Mac to debug it. It's because the font isn't loading. It's the same thing as in this comment: https://github.com/maps4print/azul/issues/5#issuecomment-421412590

> I figured that this was due to sans-serif font not present on my machine. After changing the font to arial it worked until SVG rendering.

Can you look into the /src/styles/macos.css, change it to "Arial" instead of "sans-serif" and see if it works? This is a problem with the font loading, however. Theoretically it should return the system-native font (it does so on Linux and Windows).

**Comment by fschutt** [comment]
No, it's because of this line, which also tries to load the sans-serif font: https://github.com/maps4print/azul/blob/master/examples/debug.rs#L148

Also, the SVG doesn't seem to work on Mac at all - the shader doesn't draw for whatever reason. It's really strange because it should work in theory, but the font loading is based on a C library. I'll maybe switch it over to `font-kit` (which is pure Rust) and try again. But thanks for testing.

**Comment by schulzch** [comment]
I spend some time looking into this one today. As far as I can tell, the state of this bug is:
- The "debug" example starts with an empty window on macOS and windows (after fixing a few compilation errors)... this example seems to have issues with missing redraw-requests.
- Resizing the window once makes the text appear on windows, but not on macOS
- Resizing results in flickering on windows, but not on macOS
- on macOS: clicking the window results in crashing the application (no file selection appears)
- on windows: clicking the window leads to the file section and a rendered SVG; however, resizing the window to issue another draw call results in a smaller depiction (downsized) of the same SVG

I thought that maybe the OpenGL state is broken... thus to make debugging tools work I made some modifications:
```rust
// window.rs
builder = builder.with_gl_debug_flag(true);
// window.rs
let display = Display::with_debug(gl_window, DebugCallbackBehavior::PrintAll)?;
// app.rs (continuous redrawing is required for most tools to work properly)
should_redraw_window: true,
```

On macOS: Apple has removed the OpenGL debugging tools from XCode. However, they can still be downloaded (Google for "Additional XCode Developer Tools download"). Tools report nothing useful (seems to be valid OpenGL).

On windows Nvidia Nsight reports a few useless state changes and zero-fragment draw calls, but no OpenGL errors (nothing unusual, since team green does not give a damn thing about validity).

Hope it helps :)

**Comment by fschutt** [comment]
> on macOS: clicking the window results in crashing the application (no file selection appears)

Well, that's a first, since usually file selection works on Mac without a problem.

I know about the "downsized" SVG problem, it's a problem with framebuffers not getting bound with the correct sizes. The size of the framebuffer does, for some reason, get tied to the window size instead of the texture size. I am not sure why that happens and I am not sure how to fix it yet, I've just worked around it in my applications (by making the texture size the same size as the window).

**Comment by schulzch** [comment]
> Well, that's a first, since usually file selection works on Mac without a problem.

No, it is not new - the click handler is still trying to load "sans-serif" right before the file dialog shows up. I think an appropriate fix would be to have `app_resources.rs`/`get_builtin_font(...)` always return a valid font or hardcode the common "fallback font" names there? An alternative would be to have all examples use an external font such as "KoHo-Light". What's your opinion on that?

**Comment by fschutt** [comment]
Yeah, well using an external font in all examples isn't going to solve the problem: "sans-serif" should work and load the system-native sans-serif font, but it doesn't work. It's a problem with the font-loader crate that is currently used to load native fonts. I was just surprised if the file dialog itself would have crashed (which it seemingly doesn't) - it crashes before the file dialog is shown, so I agree that's not a new issue. 

The way to "properly" solve it is to fix font-loader but I'm not sure if I have the time for that. For now a "fix" would be to use "Arial" instead of sans-serif (which seems to work even on systems that don't have Arial installed for some reason) until I find time to fix the font-loading system (which has to be reworked anyway, the API is just too awful in practice).

**Comment by fschutt** [comment]
This should be fixed now, the "solution" is to redirect the string "sans-serif" to "Helvetica", which should fix this issue in particular.

**Comment by fschutt** [comment]
This should be fixed now, the "solution" is to redirect the string "sans-serif" to "Helvetica", which should fix this issue in particular.
