### ISSUE TITLE
Missing images on README

### ISSUE THREAD

**Issue by diegotoral** [maps4print/azul#197]
## Description
The `README.md` is missing the images. 😕

**Comment by diegotoral** [comment]
Just noted that images are missing on the wiki too, probably due to the same problem.

**Comment by fschutt** [comment]
Yes, I removed them (git-bfg) in order to cut down the git repo size (using an external image host instead). Otherwise, every time I update the images, it would bloat the repo by half a MB, which is a bit annoying for people who'd like to pull / push, they have to download all the images. The repo should be code-only, ideally. Thanks for reporting.

**Comment by diegotoral** [comment]
Got it! Thanks for the clarification.

**Comment by fschutt** [comment]
nah, don't close it, the images are still broken
