### ISSUE TITLE
no matching package named `azul` found

### ISSUE THREAD

**Issue by VitalyAnkh** [maps4print/azul#23]
When I followed the wiki, in the installation section I encountered a problem: cargo gave me an error and complained that "no matching package named `azul` found", just like the screenshot shows:
![_ _20181009023005](https://user-images.githubusercontent.com/24508452/46627055-cf9e5700-cb6b-11e8-9962-abc86a1d3b26.png)
I searched the crates.io and found azul indeed doesn't exist there.
![Uploading 深度截图_选择区域_20181009022846.png…]()
So what happened?

**Comment by Bobo1239** [comment]
See https://github.com/maps4print/azul/issues/10#issuecomment-421988590. Azul is not ready yet so it isn't on crates.io. If you want, you can try azul as a git dependency:
```
[dependencies]
azul = { git = "https://github.com/maps4print/azul.git"  }
```

**Comment by VitalyAnkh** [comment]
@Bobo1239 Thank you. And I think this should be added to the wiki.

**Comment by fschutt** [comment]
Fixed in https://github.com/maps4print/azul/wiki/Installation/_compare/3e498104cdf8db6f35701b82c207bf281c4fadbe...e7a2e42552f9abc7a5e63749db5f45ed5f966cea

I've also removed crates.io mentions from the readme and the website (until version 0.1 releases), so hopefully nobody will stumble upon this mistake anymore.
