### ISSUE TITLE
What about performance?

### ISSUE THREAD

**Issue by ProgrammingLife** [maps4print/azul#252]
As I am beginner to Azul I have some worries about its performance. I've read Azul uses WebRenderer engine so what does it mean? What about performance? Does it work like WebView or a similar stuff? Sorry for bothering you.

**Comment by fschutt** [comment]
WebRender is *not* a full browser. WebRender is only the "rendering" part of the browser. It only handles drawing rectangles to the screen (that alone is complicated enough, given borders, clips, scrolling clips, masks, etc.). Azul has its own layout engine that is modeled after HTML5. Azul takes the `Dom` description of your UI and calls webrender to render it to the screen. 

Azul currently uses ~7 megabytes of RAM for a hello-world app (kind of cheating, since DLL memory isn't accounted for - maybe 20 - 30MB if you include that). For comparison, Electron uses 69 MB, Qt uses 20 MB, takes around 5 - 11 ms to draw one frame to the screen (Electron has about the same performance here, Qt is faster with about 2 - 3 ms), startup time is instant (since it's compiled Rust, duh), CPU usage is between 0 (idle) and 10 percent (heavy DOM updates) - beats Electron which has higher CPU usage.

Overall, the performance of Azul is comparable with the performance of Qt in terms of resources. Not great, not terrible.

**Comment by MatthieuDartiailh** [comment]
Out of curiosity will be possible (in the future) to somehow bypass the HTML layout engine (ie only provide absolute positions) so that using a constraints based solver such as https://github.com/nucleic/kiwi becomes possible. I am maintaining the following project https://github.com/nucleic/enaml (that uses Qt as a backend) and kiwi to solve constraint. This can be more flexible than nested boxes and was wondering if that is an approach that would work in azul.

**Comment by fschutt** [comment]
> This can be more flexible than nested boxes and was wondering if that is an approach that would work in azul.

No, that constraint-solver approach was already tried and in practice it's way too complicated to describe a UI with layout constraits - [and also very slow](https://gist.github.com/fschutt/41c7d7e41b6198472e0798496f4bbc55). Imagine a table layout with 4000+ cells and each cell needs at least 6 constraints, and the fastest algorithm for solving constraints (Cassowary) is currently O(n²) at best, O(n³) at worst. With a CSS-based approach, the performance is O(n), and can even be parallelized later on. Plus, constraints are not easily debuggable and can interfere with each other due to over- / underconstrainted layouts, debugging becomes hell very very quickly.

Apple solves this by making some layout-heavy widgets (like tables) not rely on constraints, but this increases complexity. Cassowary is absolutely *not* the way to go, the original version of Azul was solved using Cassowary, and it didn't work at all.

**Comment by MatthieuDartiailh** [comment]
Thanks for your detailed answer @fschutt . 

I was not suggesting to use constraint based layout for everything (and in particular not for dealing with a table). However I do have good experience in the mentioned above project (which uses kiwi which is a faster implementation of Cassowary than the original implementation). In particular, each container has its own solver which tends to keep the size of each system small and manageable. So I am not so much asking for this to be part of azul itself but if it is something that could be used on top of it (just like enaml use Qt as a backend and has the solver specify absolute positions).

**Comment by fschutt** [comment]
You can override positioning values on a per-DOM-node basis, yes:

```css
* { 
    position: absolute; 
    top: var('pos_top' | 0px); 
    left: var('pos_left' | 0px); 
}
```
```rust
fn layout(data: RefAny, info: LayoutInfo) -> Dom {
    Dom::div()
        .with_css_override("pos_top", PixelSize::px(5.0).into()) // 5px
        .with_css_override("pos_left", PixelSize::px(10.0).into()) // 10px
}
```

This way you could implement and run your own layout solver.
