### ISSUE TITLE
Do css/dom errors fail silently?

### ISSUE THREAD

**Issue by OptimisticPeach** [maps4print/azul#28]
Do dom and css fail silently if there's an error or if it can't find a css attribute?
I ask to know for debugging apps, and their appropriate dom and css.

**Comment by fschutt** [comment]
That depends on where the error occurs and what error you mean.

The `Css::from_str()` function returns a `Result<Css, CssParsingError>` - if you `unwrap()` this result, then it will crash, obviously. The CSS has to parse correctly and doesn't allow any syntax errors. If it crashes depends on how you handle that `Result` (but CSS failing to parse is usually not something you could recover from, so I'd just crash). `Css::native()` can't fail, because it's included with the framework, so if that fails, it's an upstream error.

When hot-reloading is active (in debug mode) and the CSS contains errors, the error will be printed and the last style sheet that could be parsed is applied. This is mostly for quick iteration, which is why hot-reloading is disabled in release mode.

Applying CSS properties to DOM elements does not emit a warning, because it is unknown if a CSS class or ID is used or unused - for this, azul would need to know about all possible states of the UI, which is impossible. So, no warning is emitted.

For dynamic CSS properties, it doesn't crash if the property isn't set, it will use the default value. However if you do something like this:

```css
#my_div { width: [[ my_custom_width | 450px ]];
```
```rust
css.set_dynamic_property("my_custom_width", ("color", "blue").into().unwrap());
```
... then [this code](https://github.com/maps4print/azul/blob/25dcc41ab9a737409d46e193b25d63ff85c890d3/src/display_list.rs#L1370-L1376) will emit a warning if you have `--feature=logging` enabled.

DOM construction itself shouldn't crash. In the worst case, you get an empty DOM, but the construction of the DOM can't crash. Ex if you make a table or list with 0 elements, you just get an empty table or list, but that's not an error.

**Comment by fschutt** [comment]
Right now, yes. But it would be possible to implement warnings for those cases. However, implementing that might take a while.
