### ISSUE TITLE
How to add daemons from inside a DefaultCallback?

### ISSUE THREAD

**Issue by danjl1100** [maps4print/azul#59]
I'm fairly familiar with rust, and am just starting to learn azul's framework. Expanding on the [two-way data binding](https://github.com/maps4print/azul/wiki/Two-way-data-binding) tutorial, I'd like to add a daemon to blink a cursor within the text field.
How do you add a daemon from within a `DefaultCallback`?

It seems like you can only `add_daemon()` when `AppState<T>` or `App<T>` is available, not from the `AppStateNoData<T>` passed to default callbacks. From the docs, I gather that `AppStateNoData` is meant for use in smaller scopes without access to the main state datatype (as is the case in the two-way data binding tutorial: accessing `TextInputState` rather than `MyAppData`).
I must be missing something, otherwise all daemons would need to be added in the user code rather than the library code for each widget.

Any help is greatly appreciated. Happy to see active development on a promising light-weight GUI solution for rust.

**Comment by fschutt** [comment]
Yeah, I think you currently can't do that, which is simply an oversight on my part. I'll need to add this later to the `AppStateNoData`.

For blinking - currently there is no animation support, but in the future, this should be handled in CSS animations, so that blinking doesn't require a re-layout of the entire frame.
