### ISSUE TITLE
A Navigation Service

### ISSUE THREAD

**Issue by Weasy666** [maps4print/azul#60]
Hi! I want to implement a Navigation Service. In ran straight into some Problems.

I'm gonna tell you how I wanted to do this first. I wanted to create a struct, the `Navigation Service`, that goes into the `AppData`. To this struct you can register page structs that implements a trait `Navigable`.
Then in the `layout()` function of `AppData` you can navigate to different pages or rather switch between page structs and call their implementation of layout to different pages. So a navigation just swaps the dom the app is rendering.
``` rust
pub trait Navigable: Layout {
    // Some functions
}
```
and the Navigation Service
``` rust
pub struct NavigationService {
    pages: HashMap<String, Arc<Navigable>>,
    pub navigation_stack: VecDeque<Arc<Navigable>>,
    current_page_idx: u8,
}
impl NavigationService {
    // Some functions to actually do the navigation and return a page that implements Navigable
}
```
Next i tried to implement `Layout` for my `AppData` and call my NavigationService in it. And that's where my problems started.
``` rust
impl Layout for AppData {
    fn layout(&self, info: WindowInfo<Self>) -> Dom<Self> {
        // here i get the following error for the .layout(info) function call
        // [rustc] the `layout` method cannot be invoked on a trait object
        self.navigation_service.current_page().layout(info)
    }
}
```
When i replace the `Layout` trait with one i created myself and i call the function of this replaced trait, then i don't get the error. So.....i'm kinda at my wits end and hope you may have an idea were the real problem is, or maybe the way i'm trying to do this is totally wrong. I appreciate any help or thoughts on this.

**Comment by fschutt** [comment]
You can only implement the `Layout` trait for a struct / enum, not a trait (because `Layout` requires `Self: Sized`). This is intentional, because you can't return a `-> Dom<Navigable>` - what size would `Dom<Navigable>` have? `Navigable` is a trait, therefor it is un-sized, so `Dom<Navigable>` can't exist (the size of the `Navigable` type must be known at compile time). The signature of azuls `layout()` function requires `-> Dom<Self> where Self: Sized`, meaning `Self` can only refer to a (sized) struct or enum, not to a trait (like in your case `Navigable`).

In order to solve it, you need to restructure your app a bit - I think you're overengineering it:

```rust
struct Page { }

impl Page {
    fn render(&self) -> Dom<AppData> {
        Dom::new(NodeType::Div).with_id("page")
    }
}

struct AppData {
    pages: Vec<Page>,
    current_page_idx: usize,
}

impl Layout for AppData {
    fn layout(&self, info: WindowInfo<Self>) -> Dom<Self> {
        self.pages[self.current_page_idx].render()
    }
}
```

If you have different types of pages, I'd use an enum:

```rust
enum Page {
    WelcomePage(WelcomePageState),
    OtherPage,
}

impl Page {
    fn render() -> Dom<AppData> { /* */ }
}
```

I would not use traits until absolutely necessary, nor would I call the function `layout()` - it can get confusing to have hundreds of different `layout()` functions all throughout your codebase.

**Comment by Weasy666** [comment]
Hm...that looks good. Thanks for the advise. You are right that it is a bit overengineering...i think i'll change it to the enums and see how it works out.
But for the sake of understanding it....do you know a possible solution to "inherit" the `Layout` trait with `Navigable`? Would it work if i also "inherit" `Sized` with `Navigable` or if i implement it at the struct that implements `Navigable`?
