### ISSUE TITLE
Panic request running HelloWorld on Windows with WSL

### ISSUE THREAD

**Issue by spkellydev** [maps4print/azul#74]
## Description
Output:
```
 2018-12-07 18:31:07 ⌚  DESKTOP-4VFBHM4 in /mnt/c/Projects/rusty/my_first_azul_app
± |master ?:4 ✗| → cargo run
   Compiling my_first_azul_app v0.1.0 (/mnt/c/Projects/rusty/my_first_azul_app)
    Finished dev [unoptimized + debuginfo] target(s) in 26.76s
     Running `target/debug/my_first_azul_app`
[ERROR][azul::logging] An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: libcore/result.rs at line 1009 in thread main

Error information:
called `Result::unwrap()` on an `Err` value: X11ClipboardError(XcbConn(ClosedParseErr))

Backtrace:



sh: 1: Syntax error: Bad function name
```

Application code from Wiki
```
extern crate azul;

use azul::prelude::*;

struct MyDataModel {}

impl Layout for MyDataModel {
    fn layout(&self, _: WindowInfo<Self>) -> Dom<Self> {
        Dom::new(NodeType::Div)
    }
}

fn main() {
    let app = App::new(MyDataModel {}, AppConfig::default());
    let window = Window::new(WindowCreateOptions::default(), Css::native()).unwrap();
    app.run(window).unwrap();
}
```

## Version / OS
Windows 10
WSL Ubuntu:
```
→ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
```

**Comment by Yatekii** [comment]
I am pretty sure you are not supposed to run any UI applications from WSL. Linux uses fundamentally different approaches to graphics as opposed to Windows and thus that wont really happen.

WSL has no X11 and surely no X11 Clipboard. So it is obvious why this can't work ;) It is not a thing with Azul.

**Comment by spkellydev** [comment]
Ah, I see. Thanks for the quick response

**Comment by Keshi** [comment]
If the lack of X11 server is the only obstacle for WSL, maybe you can try running something like MobaXterm (on the Windows side).  I had success running GUI applications like Sublime Text in WSL with that before.

**Comment by fschutt** [comment]
I'm closing this because it's not possible to run X11 apps using WSL, nor is it planned by the WSL team: https://github.com/Microsoft/WSL/issues/2356. Although, I really have to wonder why what the purpose of this is - why would you compile your app for Linux, but then run it under Windows using WSL - instead of just compiling it for Windows.

WSL has simply no X11 server, so there can't be any display or GUI output. It's like you want a GUI on a PC that has no monitor, it's not gonna work. That's not the fault of azul, though. You can try using Xming or a different third-party X11 client to run your app, but you have to install it first:

- https://www.scivision.co/x11-gui-windows-subsystem-for-linux/
- https://www.ctrl.blog/entry/how-to-x-on-wsl
- https://askubuntu.com/questions/993225/whats-the-easiest-way-to-run-gui-apps-on-windows-subsystem-for-linux-as-of-2018

I'm closing this because it's not a problem that I can fix, ask the WSL team or use Xming.
