### ISSUE TITLE
StackCheckedPointer is unsound

### ISSUE THREAD

**Issue by kevinmehall** [maps4print/azul#84]
The [documentation](https://github.com/maps4print/azul/wiki/Two-way-data-binding#stack-checked-pointers) describes an assumption Azul's data binding relies on when it bypasses the borrow-checker:

> The pointer is inside the boundaries of `T` to `T + size_of::<T>()` - as long as T is alive, the pointer points to valid memory.

Unfortunately, nothing in Rust's type system guarantees this. The most obvious counterexample is `enum` types.

Here's an example showing how code without `unsafe` can cause an invalid pointer dereference and segfault using the safe interface of `TextInput`:
https://gist.github.com/kevinmehall/44190fea3e4775c90d175b2bb6c07e53
(this example could do without the `RefCell` if it were mutated elsewhere, in a callback or something).

**Comment by o01eg** [comment]
Could it be implemented via `Pin`?

**Comment by tobz1000** [comment]
As I understand it, `Pin` is a generalisation of what `StackCheckedPointer` is trying to achieve - and would allow previously-proven self-referential structures to be used where possible.

Is there any reason not to allow users to provide a `&mut TextInputState`-getter function, rather than a direct reference to the field; e.g. `textInput.bind(window, |model| &mut model.text_input, &mut model)`? I imagine the safety gain would be worth the small performance hit in many instances.
