### ISSUE TITLE
Two way data binding example code doesn't run

### ISSUE THREAD

**Issue by jlgerber** [maps4print/azul#87]
## Description
When cutting and initial two way databinding code, after making up for some inconsistencies, it will not run. The TextInputState impl references a function ```virtual_key_code_to_char``` in update_state which doesnt appear to exist in Azul. 

## Steps to Reproduce
- cut and paste code from wiki
- track down import statements required

## Expected Behavior
two way databinding example

## Actual Behavior
fails to compile

**Comment by fschutt** [comment]
Oh yeah, you meant the code from the wiki, I was confused for a second - that was because originally Azul only hard-coded translations from VirtualKeyCodes to characters, however, this doesn't work at all with Unicode input / non-ASCII character, which is why it was changed to `On::TextInput` versus `On::VirtualKeyDown`. `On::TextInput` only reacts to printable unicode characters, i.e. text input, while `On::VirtualKeyDown` also reacts to control characters, function keys, etc. and doesn't respond to keyboard layout, see #37.

It's a documentation problem, the `virtual_key_code_to_char` does not exist anymore, because now `On::TextInput` is the proper solution and instead of `.latest_virtual_keycode`, you should simply use `.current_char` which is already a unicode character (for example, to allow Russian text input). Thanks for reporting, should be fixed soon.

**Comment by X-m7** [comment]
I have a different issue with the example code, this time after adding in the imports and fixing the names of things that apparently changed I ended up with a few "expected mutable reference, found struct `azul::app::AppStateNoData`" errors, not sure where to go from there.

**Comment by fschutt** [comment]
@X-m7 Yeah, that was a change because the API changed from `fn(AppStateNoData) { }` to `fn (&mut AppStateNoData) { }` - just put a `&mut` in front of where you get the error.

**Comment by X-m7** [comment]
That got it to compile, but then it apparently does nothing when I press keys on the keyboard, same goes for the first example code. Apparently the callbacks never get called, but if I replace `On::TextInput` with `On::VirtualKeyDown` or `On::VirtualKeyUp` then it does react to key presses, although it seems that's not what they were meant for.

**Comment by fschutt** [comment]
@X-m7 You need to click on the text input field first (to focus it) and then you can enter text.

**Comment by X-m7** [comment]
I tried clicking all over the app and pressing keys, and nothing happened still. I also tried using the `:focus` CSS selector to see if it was actually focused, and apparently it never is. Here's the code I ended up with for reference, just in case this is because I did something wrong in the process of fixing the compiler errors:
```rust
extern crate azul;

use azul::app::AppStateNoData;
use azul::callbacks::DefaultCallback;
use azul::window::FakeWindow;
use std::marker::PhantomData;
use azul::callbacks::DefaultCallbackId;
use azul::prelude::*;

const CSS: &str = "
#input {
	border: 2px solid transparent;
	background-color: #ccc;
	width: 300px;
	height: 100px;
}
#input:focus {
	background-color: #fff;
}
";

struct MyAppData {
    text_input: TextInputState,
}

impl Layout for MyAppData {
    fn layout(&self, info: LayoutInfo<Self>) -> Dom<Self> {
        TextInput::new(info.window, &self.text_input, &self).dom(&self.text_input).with_id("input")
    }
}

struct TextInput<T: Layout> {
    callback_id: DefaultCallbackId,
    marker: PhantomData<T>,
}

pub struct TextInputState {
    pub text: String 
}

impl<T: Layout> TextInput<T> {

    pub fn new(
        window: &mut FakeWindow<T>, 
        state_to_bind: &TextInputState, 
        full_data_model: &T) 
    -> Self 
    {
        let ptr = StackCheckedPointer::new(full_data_model, state_to_bind).unwrap();
        let callback_id = window.add_callback(ptr, DefaultCallback(Self::update_text_field));
        Self { callback_id, marker: PhantomData }
    }

    pub fn dom(self, state_to_render: &TextInputState) -> Dom<T> {
        let mut container_div = Dom::new(NodeType::Div).with_class("text-input-container");
        container_div.add_default_callback_id(On::TextInput, self.callback_id);
        container_div.add_child(Dom::new(NodeType::Label(azul::dom::DomString::Heap(state_to_render.text.clone()))));
        container_div
    }

    fn update_text_field(
        data: &StackCheckedPointer<T>, 
        app_state_no_data: &mut AppStateNoData<T>, 
        window_event: &mut CallbackInfo<T>
    ) -> UpdateScreen {
        unsafe { data.invoke_mut(TextInputState::update_state, app_state_no_data, window_event) }
    }
}

impl TextInputState {
    pub fn update_state<T: Layout>(
        &mut self, 
        app_state: &mut AppStateNoData<T>, 
        window_event: &mut CallbackInfo<T>) 
    -> UpdateScreen 
    {
        let ch = app_state.windows[window_event.window_id].get_keyboard_state().current_char?;
        self.text.push(ch);
        Redraw
    }
}

fn main() {
    let mut app = App::new(MyAppData { text_input: TextInputState {text: String::from("Hello World!")} }, AppConfig::default()).unwrap();
    let window = app.create_window(WindowCreateOptions::default(), css::override_native(CSS).unwrap()).unwrap();
    app.run(window).unwrap();
}
`

**Comment by fschutt** [comment]
Yeah, you didn't actually make the DOM focus-able by calling `.with_tab_index(TabIndex::Auto)`. That should fix the focusing issues.

**Comment by X-m7** [comment]
That actually did fix the problem, now it works. I didn't see that fact mentioned in the wiki. Making it automatic sounds good to me, or alternatively it might be a good idea to stick this sort of thing in a FAQ section of the wiki or something like that. Anyway, thanks for replying!
